#!/bin/bash
# ntih - naming things is hard
# ntih © Mike Lalumiere 2018
# ntih [[MIN:]MAX] [COUNT] < EXAMPLE TEXT > WORDS
# This file is licensed under the GPLv3. Please see LICENSE.
#
# Here's a line encoding for a markov chain of characters in a word:
#  <char previous><char current> <char next><integer weight> ...
#
# Entries looks like this:
#  ^l a38 e24 i23 l1 o18 u9 y2
#  an $49 a11 c27 d48 e12 f1 g22 i19 k7 l1 n9 o4 q1 s54 t53 u3 w1 x1
#  nd $12 a13 b5 e42 f1 h2 i21 l12 m2 o7 p1 r5 s17 t1 u4
#  fr $1 a10 e15 i2 o9 u2 y1
#  db a3 i1 l1 u2
#
# Each rule gives possible next characters given the previous two characters.
# There are two special characters '^' and '$' denoting start and end points.
#
# To build a word a starting character is selected randomly, then for each
# step a next character is selected randomly weighted by the rules.
#
# Function ntih_render reads a chain of this format then uses it to assemble words.
# Function ntih_build generates a chain in this format by reading text input.
# Function ntih provides a friendly interface around the other functions.

# ntih_render [[MIN:]MAX] [COUNT] < CHAIN > WORD
# Read a chain and use it to generate COUNT words composed of between MIN and MAX characters.
ntih_render() {
    # patterns
    local p_word="[[:alpha:]^$]+"
    local p_int="[[:digit:]]+"
    # accept length argument
    local length="${1:-1:10}"
    if ! [[ "$length" =~ ^($p_int:)?$p_int$ ]]; then
        printf "%s\n" "Length argument must be an integer or pair of integers MIN:MAX." >&2
        return 1
    fi
    # length is a range or an absolute target
    IFS=':' read min max <<< "$length"
    if [ -z "$max" ]; then max="$min"; min=""; fi
    if [ -n "$min" ] && [ "$min" -ge "$max" ]; then
        printf "%s\n" "Minimum length must be less than maximum length." >&2
        return 1
    fi
    # accept number argument - an integer number of words to generate
    local number="${2:-1}"
    if ! [[ "$number" =~ ^$p_int$ ]]; then
        printf "%s\n" "Number argument must be an integer." >&2
        return 1
    fi
    # parse chain string into rules array
    local prev curr starts
    declare -A rules
    while read entry rest; do
        # read entry prev char
        prev="${entry:0:1}"
        if [ -z "$prev" ]; then break; fi
        if ! [[ "$prev" =~ $p_word ]]; then
            printf "%s\n" "BAD PREV IN '$entry' - $prev" >&2
            return 2
        fi
        # read entry current char
        curr="${entry:1:1}";
        if [ -z "$curr" ]; then break; fi
        if ! [[ "$curr" =~ $p_word ]]; then
            printf "%s\n" "BAD CURR '$entry' - $curr" >&2
            return 2
        fi
        # read entry rule string
        local buf=""
        read -a steps <<< "$rest"
        for step in "${steps[@]}"; do
            # character is first
            char="${step:0:1}"
            if [ -z "$char" ] || [ "$char" == "#" ]; then break; fi
            if ! [[ "$char" =~ $p_word ]]; then
                printf "%s\n" "BAD NEXT '$entry' - $index $char" >&2
                return 2
            fi
            # the rest is integer weight
            weight="${step:1}"
            if ! [[ "$weight" =~ $p_int ]]; then
                printf "%s\n" "BAD WEIGHT $index $weight" >&2
                return 2
            fi
            # unpack the step into a character sequence by weight
            for ((rep=0; rep < "$weight"; rep++)); do buf+="${char}"; done
        done
        # record any starting points
        if [ "$prev" == "^" ] && [ "$curr" != "^" ]; then starts+="$curr"; fi
        # record entry
        rules["${prev#^}${curr}"]="$buf"
    done
    # ensure rules exist
    if [ "${#rules[@]}" == 0 ]; then
        printf "%s\n" "No rules found!" >&2
        return 3
    fi
    # get starting character state
    local init="${rules[^]:-$starts}"
    if [ -z "$init" ]; then
        printf "Could not find initial state." >&2
        return 3
    fi
    # generate some strings from given rules
    declare -A words
    while (( "${#words[@]}" < "$number" )); do
        # for ((n=0; n < "$number"; n++)); do
        local out=""
        # setup initial state
        prev="${init:$((RANDOM % ${#init})):1}"
        rule="${rules[$prev]}"
        # walk chain until max length
        for ((len=1; len <= "$max"; len++)); do
            out+="$prev"
            # maybe end if minimum length reached
            if [ -n "$min" ] &&
                   [ "$len" -ge "$min" ] &&
                   [ "$(( RANDOM % (1 + max - len) ))" == "1" ]; then
                break
            fi
            # get next character and rule
            curr="${rule:$((RANDOM % ${#rule})):1}"
            rule="${rules[${prev}${curr}]}"
            # terminal symbol? start a new word
            if [ "$curr" == '$' ] || [ -z "$rule" ]; then
                prev="${init:$((RANDOM % ${#init})):1}"
                rule="${rules[${prev}]}"
                continue
            fi
            # step forward
            prev="$curr"
        done
        # add unique words
        let words["$out"]++
    done
    # write out words
    while read word; do
        printf "%s\n" "$word";
    done < <(printf "%s\n" "${!words[@]}" | sort)
}

# ntih_build [WEIGHT] < WORDS > CHAIN
# Build a chain from input text.
# Given integer argument WEIGHT limit rule weight to that value.
ntih_build() {
    # patterns
    local p_word="^[[:alpha:]^$]+"
    local p_int="[[:digit:]]+"
    local p_char="[[:alpha:]]"
    # arguments
    local max="${1:-10}"
    if ! [[ "$max" =~ ^($p_int:)?$p_int$ ]]; then
        printf "%s\n" "Maximum rule weight must be an integer." >&2
        return 1
    fi
    # gather character pattern data
    declare -A rules
    local prev curr
    # generate frequency strings for each rule from input
    while read line; do
        # each line into words
        while read -d ' ' word; do
            # setup the initial character state for the rule
            prev="^"
            curr="^"
            # read the rest of the word one character at a time
            while read -N1 char; do
                if ! [[ "$char" =~ ^$p_char$ ]]; then continue; fi
                # record this character as appearing after the previous two
                rules["${prev}${curr}"]+="$char"
                # step forward
                prev="$curr"
                curr="$char"
            done < <(printf "%s" "${word:1}")
            # maybe this sequence had no useful characters
            if [ "${prev}${curr}" == "^^" ]; then continue; fi
            # record end of word
            rules["${prev}${curr}"]+='$'
        done < <(printf "%s " "${line,,}")
    done
    # render sequence frequency strings into markov chain strings
    declare -A count
    declare -a steps
    for item in "${!rules[@]}"; do
        # count characters in rule string to guage a weight
        count=()
        while read -N 1 char; do
            let count["$char"]++
        done < <(printf "%s" "${rules[$item]}")
        # limit each character weight to the maximum
        for char in "${!count[@]}"; do
            if [ "${count[$char]}" -gt "$max" ]; then count["$char"]="$max"; fi
        done
        # generate next character weight strings
        steps=()
        while read char; do
            steps+=("${char}${count[$char]}")
        done < <(printf "%s\n" "${!count[@]}" | sort)
        # write this chain rule
        printf "%s %s\n" "$item" "$(printf "%s " "${steps[@]}")"
    done
}

# ntih [OPTIONS] [[MIN:]MAX] [COUNT] < TEXT > WORDS
# Generate words from chain made from input text.
ntih() {
    # usage
    read -r -d '' use <<EOF
USAGE: ntih [OPTIONS] [[MIN:]MAX] [COUNT]

Generate COUNT words each composed of between MIN and MAX characters.
Given MAX and not MIN generate words of exactly that length.

OPTIONS
 -f CHAIN_FILE  : File where the chain will be stored.
 -i INPUT_FILE  : Input file from which to read sample words.
 -r             : Force regeneration of CHAIN_FILE.
 -w MAX_WEIGHT  : Maximum rule weight during chain generation.

ENVIRONMENT
 NTIHFILE : Sets CHAIN_FILE. The default is '$HOME/.ntih'.
 NTIHDICT : Sets INPUT_FILE. The default is '/usr/share/dict/words'.

ntih © Mike Lalumiere 2018
EOF
    # environment
    local conf="${NTIHFILE:-$HOME/.ntih}"
    local dict="${NTIHDICT:-/usr/share/dict/words}"
    local regn=0
    local maxw=10
    # accept options
    local chain
    while getopts ":f:hi:rw:" opt; do
        case "$opt" in
            f) conf="$OPTARG"                                  ;;
            i) dict="$OPTARG"                                  ;;
            r) regn=1                                          ;;
            w) maxw="$OPTARG"                                  ;;
            h) printf "%s\n" "$use" >&2; return 0              ;;
            *) printf "Bad option!\n%s\n" "$use" >&2; return 1 ;;
        esac
    done
    shift $((OPTIND - 1))
    # lacking a cache generate one
    if ! [ -f "$conf" ] || [ "$regn" != 0 ]; then
        { if ! [ -t 0 ]; then
              printf "Building chain from STDIN.\n" >&2
              cat /dev/stdin
          elif [ -f "$dict" ]; then
              printf "Building chain %s from %s.\n" "$conf" "$dict" >&2
              cat "$dict"
          else
              printf "Dictionary file %s does not exist.\n" "$dict" >&2
              return 2
          fi
        } | ntih_build "$maxw" | sort > "$conf";
    fi
    # generate some strings
    ntih_render "$@" < "$conf"
}

# run it unless sourced
if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then ntih "$@"; fi
